# Generated by Django 2.0.5 on 2018-05-13 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('P', '小学'), ('J', '初中'), ('S', '高中'), ('U', '本科'), ('G', '硕士')], max_length=1)),
                ('begin', models.DateField(verbose_name='Begin Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('school', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('begin', models.DateField(verbose_name='Begin Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('N', '未定义'), ('M', '男'), ('W', '女'), ('O', '其他')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp3.User'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp3.User'),
        ),
    ]
