# Generated by Django 2.0.5 on 2018-05-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp3', '0002_auto_20180513_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField(verbose_name='Update date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp3.User')),
            ],
        ),
    ]
