# Generated by Django 2.0.5 on 2018-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp3', '0003_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(to='exp3.User'),
        ),
    ]
